"""Hand-tracking pipeline: state, geometry, color, motion, tracker, scores, pipeline."""

# Lazy imports so that "from ... hand_tracking.geometry import box_center" does not pull cv2.

def __getattr__(name: str):
    _modules = {
        "box_center": "geometry",
        "box_distance": "geometry",
        "box_velocity": "geometry",
        "expand_box": "geometry",
        "geometry_score": "geometry",
        "predict_next_box": "geometry",
        "color_mask": "color",
        "color_similarity": "color",
        "compute_color_stats": "color",
        "update_color_model": "color",
        "init_kalman": "kalman",
        "kalman_predict": "kalman",
        "kalman_update": "kalman",
        "compute_motion_mask": "motion",
        "flow_box_from_points": "motion",
        "motion_score": "motion",
        "optical_flow_points": "motion",
        "process_first_frame": "pipeline",
        "process_frame": "pipeline",
        "reinitialize_from_detection": "pipeline",
        "run_detector": "pipeline",
        "should_run_detector": "pipeline",
        "combine_scores": "scores",
        "compute_color_score": "scores",
        "compute_detector_score": "scores",
        "compute_geometry_score": "scores",
        "compute_motion_score": "scores",
        "compute_tracker_score": "scores",
        "choose_best_candidate": "search",
        "extract_roi": "search",
        "find_candidates_in_roi": "search",
        "init_track_state": "state",
        "is_track_weak": "state",
        "mark_track_weak": "state",
        "update_track_state": "state",
        "init_tracker": "tracker",
        "tracker_score": "tracker",
        "update_tracker": "tracker",
    }
    if name in _modules:
        mod = _modules[name]
        import importlib
        sub = importlib.import_module(f"src.task_detection.hand_tracking.{mod}")
        return getattr(sub, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "box_center",
    "box_distance",
    "box_velocity",
    "choose_best_candidate",
    "color_mask",
    "color_similarity",
    "combine_scores",
    "compute_color_score",
    "compute_color_stats",
    "compute_detector_score",
    "compute_geometry_score",
    "compute_motion_mask",
    "compute_motion_score",
    "compute_tracker_score",
    "expand_box",
    "extract_roi",
    "find_candidates_in_roi",
    "flow_box_from_points",
    "geometry_score",
    "init_kalman",
    "init_track_state",
    "init_tracker",
    "is_track_weak",
    "kalman_predict",
    "kalman_update",
    "mark_track_weak",
    "motion_score",
    "optical_flow_points",
    "predict_next_box",
    "process_first_frame",
    "process_frame",
    "reinitialize_from_detection",
    "run_detector",
    "should_run_detector",
    "tracker_score",
    "update_color_model",
    "update_track_state",
    "update_tracker",
]
